#!/usr/bin/env bash

# First prettier
# Adapted from: https://prettier.io/docs/en/precommit.html#option-6-shell-script

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | npx --yes prettier@3.0.0 --ignore-unknown --write

# Now eslint
# Some copied from https://gist.github.com/linhmtran168/2286aeafe747e78f53bf

PASS=true

cd hyperbee || exit 1
for file in $(git diff --cached --name-only --diff-filter=ACMR . | sed 's| |\\ |g')
do
    if npx --no eslint ../"$file"; then
    printf "\t\033[32mESLint Passed: %s\033[0m" "$file"
  else
    printf "\t\033[41mESLint Failed: %s\033[0m" "$file"
    PASS=false
  fi
done

cd ../uwazi/entity-page || exit 1
for file in $(git diff --cached --name-only --diff-filter=ACMR . | sed 's| |\\ |g')
do
    if npx --no eslint ../../"$file"; then
    printf "\t\033[32mESLint Passed: %s\033[0m" "$file"
  else
    printf "\t\033[41mESLint Failed: %s\033[0m" "$file"
    PASS=false
  fi
done


if ! $PASS; then
    exit 1
fi

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
