#!/usr/bin/env bash

# prettier: some copied from https://prettier.io/docs/en/precommit.html#option-6-shell-script
# eslint: some copied from https://gist.github.com/linhmtran168/2286aeafe747e78f53bf

PASS=true

cd hyperbee || exit 1
for file in $(git diff --cached --name-only --diff-filter=ACMR . | sed 's| |\\ |g')
do
    npx prettier --ignore-unknown --write ../"$file"
    
    if npx --no-install eslint --quiet ../"$file"; then
    printf "\t\033[32mESLint Passed: %s\033[0m\n" "$file"
  else
    printf "\t\033[41mESLint Failed: %s\033[0m\n" "$file"
    PASS=false
  fi
done

cd ../uwazi/entity-page || exit 1
for file in $(git diff --cached --name-only --diff-filter=ACMR . | sed 's| |\\ |g')
do
    npx prettier --ignore-unknown --write ../../"$file"

    if npx --no-install eslint --quiet ../../"$file"; then
    printf "\t\033[32mESLint Passed: %s\033[0m\n" "$file"
  else
    printf "\t\033[41mESLint Failed: %s\033[0m\n" "$file"
    PASS=false
  fi
done


if ! $PASS; then
    exit 1
fi

cd ../.. || exit 1

# Add back the modified/prettified files to staging
git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | xargs git add

exit 0
